## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function
## This function accepts an input of a square matrix object.
## If no input is provided, it randomly generates a square matrix object and the elements of the square matrix based on the parameters: 
		## min_dim - minimum possible dimention of the matrix, eg. 2 x 2
		## max_dim - maximum possible dimention of the matrix, eg. 10 x 10
		## min_val - minimum possible value of an element in the square matrix
		## max_val - maximum possible value of an element in the square matrix
## The inverse of the matrix is then generated with the solve(x) function and both the matrix & inverse matrix are cached.
## A status message will be returned after every task.

makeCacheMatrix <- function(x = matrix()) 
{
	if(class(x)=='matrix')
	{
		if(is.na(x[length(x)]))
		{
			min_dim<-2 # minimum possible dimention of the matrix, 2 x 2
			max_dim<-10 # maximum possible dimention of the matrix, 10 x 10
			min_val<--100 # minimum possible value of an element in the square matrix
			max_val<-100 # maximum possible value of an element in the square matrix
			matrixdim<-round(runif(1,min_dim,max_dim))
			x<-matrix(round(runif(matrixdim*matrixdim,min_val,max_val)),nrow=matrixdim,ncol=matrixdim)
			getCacheMatrix<<-x
			getCacheInverseMatrix<<-solve(x)
			check<<-1
			status_msg<<-paste('A ',nrow(x),' x ', ncol(x),' SQUARE MATRIX IS GENERATED, INVERSED & CACHED.', sep='')
			status_msg

		}
		else if(nrow(x)!=ncol(x))
		{
			check<<-0
			status_msg<<-paste('INPUT ISN\'T A SQUARE MATRIX. IT IS ',nrow(x),' x ', ncol(x),'.', sep='')
			status_msg
		}
		else
		{
			getCacheMatrix<<-x
			getCacheInverseMatrix<<-solve(x)
			check<<-1
			status_msg<<-paste('A ',nrow(x),' x ', ncol(x),' SQUARE MATRIX INPUT IS ACCEPTED, INVERSED & CACHED.', sep='')
			status_msg
		}
	}
	else
	{
		check<<-0
		status_msg<<-paste('INPUT IS A ',casefold(class(x), upper='TRUE'),'. IF AN INPUT IS NECESSARY, PLEASE USE A SQUARE MATRIX.',sep='')
		status_msg
	}
}



## Write a short comment describing this function
## This function accepts an input of a square matrix object.
## If the input is similar to the matrix generated by makeCacheMatrix()
## and if the inverse has already been calculated, then cacheSolve() will retrieve the inverse from the cache.
## If the square matrix has changed, cacheSolve() will calculate the inverse of the matrix.
## The inverse matrix will be returned.
## Enter S.2 to display the trigger points of cacheSolve()

cacheSolve <- function(x, ...) 
{
	check<<-0
	S.1<<-NULL
	S.2<<-NULL
	if(exists('getCacheMatrix')&&class(x)=='matrix')
	{
		if((nrow(x)==nrow(getCacheMatrix))&&(ncol(x)==ncol(getCacheMatrix)))
		{
			if(table(sapply(1:ncol(getCacheMatrix),function(n){getCacheMatrix[n,]==x[n,]}))["TRUE"]==length(getCacheMatrix))
			{	
				## Return a matrix that is the inverse of 'x'
				check<<-1
				S.1<<-paste('1:INVERSE MATRIX RETRIEVED FROM CACHE')
			}
			else 
			{
				makeCacheMatrix(x)
				S.1<<-paste('2:INPUT NOT FOUND IN CACHE. makeCacheMatrix CALLED. ',status_msg,sep='')
			}
		}
		else
		{
			makeCacheMatrix(x)
			S.1<<-paste('3:INPUT NOT FOUND IN CACHE. makeCacheMatrix CALLED. ',status_msg,sep='')
		}
	}
	else 
	{
		makeCacheMatrix(x)
		S.1<<-paste('4:INPUT NOT FOUND IN CACHE. makeCacheMatrix CALLED. ',status_msg,sep='')
	}

	if(check==1)
	{
		S.2<<-S.1
		getCacheInverseMatrix
	}
	else
	{
		S.2<<-S.1
		status_msg
	}
}